changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
url=jdbc:mysql://bookstore.clsaao2oey1f.ap-southeast-2.rds.amazonaws.com/bookservice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
username=root
password=4l#]AjEiSe<GGV8D)f8Po2TN:)F]
